### ISSUE TITLE
Концепция. Редактор условия выполнения Activity

### ISSUE THREAD

**Issue by Fess59** [Fess59/FE#7]
Для презентации подготовить визуализацию процесса настройки условий:
- [ ] 1. Добавление условия - вводим приоритет, условие и описание
- [ ] 2. Условие падает в список ниже, который формируется по следующей схеме:
    - [ ] 2.1 Сортировка первого уровня - сначала всегда выполняется AND затем OR
    - [ ] 2.2 Сортировка второго уровня - приоритет
- [ ] 3. Добавить индекс - для мониторинга на каком этапе схемы остановились. Если одно из условий не выполнено последующие вызваны не будут
- [ ] 4. Визуализация схемы
- [ ] 4.1 Автогенерация схемы
- [ ] 4.2 Возможность ввести тестовые данные

**Comment by Fess59** [comment]
Пример:
 /// ВАЖНО группы выполнения формируются динамически по приоритету и типу группы, кейс набор событий:
    /// 1. 1000 AND = (2==2) && (2==2) 
    /// 2. 1000 OR = (1==2) || (2==1)
    /// 3. 1100 OR = (1==2) || (2==2)
    /// 4. 1100 AND = (2==2) && (2==2) 
    /// Будет выполнено следующим образом в порядеке котором расположены пункты = (1 AND 2) AND (4 AND 3)
    /// В первых скобках сначала выполнить 1 потом выполниться 2, во вторыйх снача 4 потом 3
    /// Кейсе выше цепочка не выполниться из-за пункта 2 и не будет проверять 3 и 4 пункты
